export const dinnerItemsList = [
  "Spaghetti",
  "Grilled Chicken",
  "Dinner Salad",
  "Salmon",
  "Fajitas",
  "Tacos",
  "Momos",
  "Fried Rice",
  "Soup",
  "Nachos",
  "Curry Chicken",
  "Pork",
  "Stuffed Chicken",
  "Piccata",
  "Stuffed Potatoes",
];
